### PR TITLE
Add title-case case converter

### PR DESCRIPTION
**Pull request by mawildoer**
In my case, I'm using this to make titles from Pascal-cased `class`-names

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
Thanks for the contrib. Will get it released in the next few days.

**Review by chrisdoherty4 — APPROVED** [review]

**Comment by mawildoer** [comment]
Bump on the release @chrisdoherty4 . If you're keen on any test data, we're using the forked version in [atopile](https://github.com/atopile/atopile) without any errors we've noticed

**Comment by chrisdoherty4** [comment]
@mawildoer this slipped through the cracks. 

Will sort it tomorrow.

**Comment by mawildoer** [comment]
Hey mate, hate to bother you, but love to have this up to use via pypi! Anything I can lend a hand with?

**Comment by chrisdoherty4** [comment]
@mawildoer Apologies for the delay. All should be done now.

**Comment by chrisdoherty4** [comment]
Side note, you've motivated me to automate the release.

**Comment by mawildoer** [comment]
Not at all! Thanks for the awesome library!

**Pull request merged**
